function Export-ReportToHTML {
    <#
    .SYNOPSIS
        Exports an enterprise report to HTML format.

    .DESCRIPTION
        Generates a professional HTML report with responsive design,
        sortable tables, and optional charts. Suitable for email
        distribution or web hosting.

    .PARAMETER Report
        The report object from New-EnterpriseReport.

    .PARAMETER Path
        Output file path for the HTML report.

    .PARAMETER Open
        Open the report in default browser after generation.

    .PARAMETER EmbedStyles
        Embed CSS styles inline (useful for email).

    .EXAMPLE
        $report | Export-ReportToHTML -Path "C:\Reports\Report.html" -Open

    .EXAMPLE
        $report | Export-ReportToHTML -Path "C:\Reports\Report.html" -EmbedStyles
    #>
    [CmdletBinding()]
    [OutputType([PSCustomObject])]
    param(
        [Parameter(Mandatory = $true, ValueFromPipeline = $true)]
        [ValidateNotNull()]
        [PSTypeName('EnterpriseReport')]
        $Report,

        [Parameter(Mandatory = $true)]
        [ValidateScript({
            $parent = Split-Path $_ -Parent
            if ($parent -and -not (Test-Path $parent -PathType Container)) {
                throw "Parent directory does not exist: $parent"
            }
            $true
        })]
        [string]$Path,

        [Parameter(Mandatory = $false)]
        [switch]$Open,

        [Parameter(Mandatory = $false)]
        [switch]$EmbedStyles
    )

    process {
        try {
            # CSS Styles
            $css = Get-ReportCSS -Template $Report.Template

            # Build HTML
            $html = @"
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="$($Report.Author)">
    <meta name="generator" content="EnterpriseReporting PowerShell Module">
    <title>$($Report.Title)</title>
    $css
</head>
<body>
    <div class="report-header">
        <div class="header-content">
"@

            # Add logo if provided
            if ($Report.LogoPath -and (Test-Path $Report.LogoPath)) {
                $logoData = [Convert]::ToBase64String([System.IO.File]::ReadAllBytes($Report.LogoPath))
                $logoExt = [System.IO.Path]::GetExtension($Report.LogoPath).TrimStart('.')
                $html += @"
            <img src="data:image/$logoExt;base64,$logoData" alt="Logo" class="company-logo">
"@
            }

            $html += @"
            <h1>$($Report.Title)</h1>
            <p class="description">$($Report.Description)</p>
            <div class="meta">
                <span>Generated: $($Report.CreatedAt.ToString('yyyy-MM-dd HH:mm:ss')) UTC</span> |
                <span>Author: $($Report.Author)</span> |
                <span>System: $($Report.GeneratedOn)</span>
            </div>
        </div>
    </div>

    <div class="report-body">
"@

            # Add sections
            foreach ($section in $Report.Sections) {
                $html += @"
        <div class="section">
            <h2>$($section.Name)</h2>
"@
                if ($section.Description) {
                    $html += "            <p class=\"section-description\">$($section.Description)</p>`n"
                }

                if ($section.Data) {
                    $tableHtml = ConvertTo-HTMLTable -Data $section.Data
                    $html += $tableHtml
                }

                $html += "        </div>`n"
            }

            # Add tables
            foreach ($table in $Report.Tables) {
                $html += @"
        <div class="section">
            <h2>$($table.Name)</h2>
"@
                if ($table.Data) {
                    $tableHtml = ConvertTo-HTMLTable -Data $table.Data -Columns $table.Columns
                    $html += $tableHtml
                }

                $html += "        </div>`n"
            }

            # Add charts (basic HTML representation)
            foreach ($chart in $Report.Charts) {
                $html += @"
        <div class="section">
            <h2>$($chart.Name)</h2>
            <div class="chart-container">
"@
                $chartHtml = ConvertTo-HTMLChart -ChartData $chart.Data -Type $chart.Type -Name $chart.Name
                $html += $chartHtml

                $html += @"
            </div>
        </div>
"@
            }

            # Footer
            $html += @"
    </div>

    <div class="footer">
        <p>Report generated by EnterpriseReporting Module | $($Report.CompanyName)</p>
        <p>Generated on $($env:COMPUTERNAME) by $($env:USERNAME)</p>
    </div>

    <script>
        // Sortable tables
        document.querySelectorAll('th.sortable').forEach(header => {
            header.addEventListener('click', () => {
                const table = header.closest('table');
                const tbody = table.querySelector('tbody');
                const index = Array.from(header.parentNode.children).indexOf(header);
                const rows = Array.from(tbody.querySelectorAll('tr'));
                const direction = header.dataset.direction === 'asc' ? 'desc' : 'asc';

                header.dataset.direction = direction;

                // Remove sort indicators from other headers
                table.querySelectorAll('th').forEach(h => h.classList.remove('sort-asc', 'sort-desc'));
                header.classList.add('sort-' + direction);

                rows.sort((a, b) => {
                    const aVal = a.children[index].textContent.trim();
                    const bVal = b.children[index].textContent.trim();

                    // Try numeric sort
                    const aNum = parseFloat(aVal);
                    const bNum = parseFloat(bVal);

                    if (!isNaN(aNum) && !isNaN(bNum)) {
                        return direction === 'asc' ? aNum - bNum : bNum - aNum;
                    }

                    // String sort
                    return direction === 'asc'
                        ? aVal.localeCompare(bVal, undefined, {numeric: true})
                        : bVal.localeCompare(aVal, undefined, {numeric: true});
                });

                rows.forEach(row => tbody.appendChild(row));
            });
        });

        // Print button
        function printReport() {
            window.print();
        }
    </script>
</body>
</html>
"@

            # Write to file
            $html | Out-File -FilePath $Path -Encoding UTF8 -Force

            if ($Open) {
                Start-Process $Path
            }

            return [PSCustomObject]@{
                Path      = $Path
                Size      = (Get-Item $Path).Length
                Generated = [DateTime]::UtcNow
                Template  = $Report.Template
            }
        }
        catch {
            throw "Failed to export report to HTML: $($_.Exception.Message)"
        }
    }
}
